name: Download Artifact
description: Download a named artifact
inputs:
  UET_ARTIFACT_NAME:
    description: "The known name of the artifact."
    required: true
  UET_FRAMEWORK_TARGET:
    description: "The .NET framework identifier."
    required: true
runs:
  using: 'composite'
  steps:
    - name: Download Timestamp
      if: ${{ inputs.UET_ARTIFACT_NAME == 'timestamp' }}
      uses: actions/download-artifact@v4
      with:
        name: timestamp
        path: ""
        merge-multiple: true

    - name: Download AutoDiscovery
      if: ${{ inputs.UET_ARTIFACT_NAME == 'autodiscovery' }}
      uses: actions/download-artifact@v4
      with:
        name: autodiscovery
        path: UET/
        merge-multiple: true
    - name: Download Mac Logging
      if: ${{ inputs.UET_ARTIFACT_NAME == 'mac-logging' }}
      uses: actions/download-artifact@v4
      with:
        name: mac-logging
        path: UET/
        merge-multiple: true

    - name: Download UEFS Win
      if: ${{ inputs.UET_ARTIFACT_NAME == 'uefs-win' }}
      uses: actions/download-artifact@v4
      with:
        name: uefs-win
        path: UET/
        merge-multiple: true
    - name: Download Shim Win
      if: ${{ inputs.UET_ARTIFACT_NAME == 'shim-win' }}
      uses: actions/download-artifact@v4
      with:
        name: shim-win
        path: UET/uet.shim/bin/Release/${{ inputs.UET_FRAMEWORK_TARGET }}/win-x64/publish/
        merge-multiple: true
    - name: Download Pass 1 Win
      if: ${{ inputs.UET_ARTIFACT_NAME == 'pass-1-win' }}
      uses: actions/download-artifact@v4
      with:
        name: pass-1-win
        path: UET/uet/bin/Release/${{ inputs.UET_FRAMEWORK_TARGET }}/win-x64/publish/
        merge-multiple: true
    - name: Download Pass 2 Win
      if: ${{ inputs.UET_ARTIFACT_NAME == 'pass-2-win' }}
      uses: actions/download-artifact@v4
      with:
        name: pass-2-win
        path: UET/uet/bin/Release/${{ inputs.UET_FRAMEWORK_TARGET }}/win-x64/publish/
        merge-multiple: true
        
    - name: Download UEFS Mac
      if: ${{ inputs.UET_ARTIFACT_NAME == 'uefs-mac' }}
      uses: actions/download-artifact@v4
      with:
        name: uefs-mac
        path: UET/
        merge-multiple: true
    - name: Download Shim Mac
      if: ${{ inputs.UET_ARTIFACT_NAME == 'shim-mac' }}
      uses: actions/download-artifact@v4
      with:
        name: shim-mac
        path: UET/uet.shim/bin/Release/${{ inputs.UET_FRAMEWORK_TARGET }}/osx-arm64/publish/
        merge-multiple: true
    - name: Download Pass 1 Mac
      if: ${{ inputs.UET_ARTIFACT_NAME == 'pass-1-mac' }}
      uses: actions/download-artifact@v4
      with:
        name: pass-1-mac
        path: UET/uet/bin/Release/${{ inputs.UET_FRAMEWORK_TARGET }}/osx-arm64/publish/
        merge-multiple: true
    - name: Download Pass 2 Mac
      if: ${{ inputs.UET_ARTIFACT_NAME == 'pass-2-mac' }}
      uses: actions/download-artifact@v4
      with:
        name: pass-2-mac
        path: UET/uet/bin/Release/${{ inputs.UET_FRAMEWORK_TARGET }}/osx-arm64/publish/
        merge-multiple: true
        
    - name: Download Shim Linux
      if: ${{ inputs.UET_ARTIFACT_NAME == 'shim-linux' }}
      uses: actions/download-artifact@v4
      with:
        name: shim-linux
        path: UET/uet.shim/bin/Release/${{ inputs.UET_FRAMEWORK_TARGET }}/linux-x64/publish/
        merge-multiple: true
    - name: Download Pass 1 Linux
      if: ${{ inputs.UET_ARTIFACT_NAME == 'pass-1-linux' }}
      uses: actions/download-artifact@v4
      with:
        name: pass-1-linux
        path: UET/uet/bin/Release/${{ inputs.UET_FRAMEWORK_TARGET }}/linux-x64/publish/
        merge-multiple: true
    - name: Download Pass 2 Linux
      if: ${{ inputs.UET_ARTIFACT_NAME == 'pass-2-linux' }}
      uses: actions/download-artifact@v4
      with:
        name: pass-2-linux
        path: UET/uet/bin/Release/${{ inputs.UET_FRAMEWORK_TARGET }}/linux-x64/publish/
        merge-multiple: true

    - name: Download Libs Win
      if: ${{ inputs.UET_ARTIFACT_NAME == 'libs-win' }}
      uses: actions/download-artifact@v4
      with:
        name: libs-win
        path: UET/
        merge-multiple: true
    - name: Download Libs Mac
      if: ${{ inputs.UET_ARTIFACT_NAME == 'libs-mac' }}
      uses: actions/download-artifact@v4
      with:
        name: libs-mac
        path: UET/
        merge-multiple: true