// <auto-generated />
using System;
using Io.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Io.Migrations
{
    [DbContext(typeof(IoDbContext))]
    [Migration("20220415173722_NullableUpdate")]
    partial class NullableUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Io.Database.BuildEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("AllowFailure")
                        .HasColumnType("boolean");

                    b.Property<string>("ArtifactsFilename")
                        .HasColumnType("text");

                    b.Property<long?>("ArtifactsSize")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DownstreamPipelineId")
                        .HasColumnType("bigint");

                    b.Property<long?>("Duration")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastUpdatedByWebhookEventId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Manual")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("PipelineId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RunnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Stage")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("When")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DownstreamPipelineId")
                        .IsUnique();

                    b.HasIndex("PipelineId");

                    b.HasIndex("RunnerId");

                    b.HasIndex("UserId");

                    b.ToTable("Builds");
                });

            modelBuilder.Entity("Io.Database.BuildEstimations", b =>
                {
                    b.Property<long>("BuildId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("EstimatedFinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasIndex("BuildId")
                        .IsUnique();

                    b.ToView("BuildEstimations");
                });

            modelBuilder.Entity("Io.Database.CommitEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AuthorEmail")
                        .HasColumnType("text");

                    b.Property<string>("AuthorName")
                        .HasColumnType("text");

                    b.Property<long>("LastUpdatedByWebhookEventId")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Timestamp")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Commits");
                });

            modelBuilder.Entity("Io.Database.MergeRequestEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("InternalId")
                        .HasColumnType("bigint");

                    b.Property<long>("LastUpdatedByWebhookEventId")
                        .HasColumnType("bigint");

                    b.Property<string>("MergeStatus")
                        .HasColumnType("text");

                    b.Property<string>("SourceBranch")
                        .HasColumnType("text");

                    b.Property<long?>("SourceProjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("TargetBranch")
                        .HasColumnType("text");

                    b.Property<long?>("TargetProjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MergeRequests");
                });

            modelBuilder.Entity("Io.Database.PipelineEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CommitId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailedStatus")
                        .HasColumnType("text");

                    b.Property<long?>("Duration")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastUpdatedByWebhookEventId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MergeRequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("PreviousSha")
                        .HasColumnType("text");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<long?>("QueuedDuration")
                        .HasColumnType("bigint");

                    b.Property<string>("Ref")
                        .HasColumnType("text");

                    b.Property<string>("Sha")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string[]>("Stages")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<bool?>("Tag")
                        .HasColumnType("boolean");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CommitId");

                    b.HasIndex("MergeRequestId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Pipelines");
                });

            modelBuilder.Entity("Io.Database.PipelineEstimations", b =>
                {
                    b.Property<DateTimeOffset?>("EstimatedFinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PipelineId")
                        .HasColumnType("bigint");

                    b.HasIndex("PipelineId")
                        .IsUnique();

                    b.ToView("PipelineEstimations");
                });

            modelBuilder.Entity("Io.Database.ProjectEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("DefaultBranch")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GitHttpUrl")
                        .HasColumnType("text");

                    b.Property<string>("GitSshUrl")
                        .HasColumnType("text");

                    b.Property<long>("LastUpdatedByWebhookEventId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Namespace")
                        .HasColumnType("text");

                    b.Property<string>("PathWithNamespace")
                        .HasColumnType("text");

                    b.Property<long?>("VisibilityLevel")
                        .HasColumnType("bigint");

                    b.Property<string>("WebUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Io.Database.RunnerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool?>("IsShared")
                        .HasColumnType("boolean");

                    b.Property<long>("LastUpdatedByWebhookEventId")
                        .HasColumnType("bigint");

                    b.Property<string>("RunnerType")
                        .HasColumnType("text");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Runners");
                });

            modelBuilder.Entity("Io.Database.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<long>("LastUpdatedByWebhookEventId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Io.Database.WebhookEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("Data")
                        .HasColumnType("json");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("WebhookEventEntity");
                });

            modelBuilder.Entity("Io.Database.BuildEntity", b =>
                {
                    b.HasOne("Io.Database.PipelineEntity", "DownstreamPipeline")
                        .WithOne("UpstreamBuild")
                        .HasForeignKey("Io.Database.BuildEntity", "DownstreamPipelineId");

                    b.HasOne("Io.Database.PipelineEntity", "Pipeline")
                        .WithMany("Builds")
                        .HasForeignKey("PipelineId");

                    b.HasOne("Io.Database.RunnerEntity", "Runner")
                        .WithMany("Builds")
                        .HasForeignKey("RunnerId");

                    b.HasOne("Io.Database.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("DownstreamPipeline");

                    b.Navigation("Pipeline");

                    b.Navigation("Runner");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Io.Database.BuildEstimations", b =>
                {
                    b.HasOne("Io.Database.BuildEntity", "Build")
                        .WithOne()
                        .HasForeignKey("Io.Database.BuildEstimations", "BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Build");
                });

            modelBuilder.Entity("Io.Database.PipelineEntity", b =>
                {
                    b.HasOne("Io.Database.CommitEntity", "Commit")
                        .WithMany()
                        .HasForeignKey("CommitId");

                    b.HasOne("Io.Database.MergeRequestEntity", "MergeRequest")
                        .WithMany()
                        .HasForeignKey("MergeRequestId");

                    b.HasOne("Io.Database.ProjectEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("Io.Database.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Commit");

                    b.Navigation("MergeRequest");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Io.Database.PipelineEstimations", b =>
                {
                    b.HasOne("Io.Database.PipelineEntity", "Pipeline")
                        .WithOne()
                        .HasForeignKey("Io.Database.PipelineEstimations", "PipelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pipeline");
                });

            modelBuilder.Entity("Io.Database.WebhookEventEntity", b =>
                {
                    b.HasOne("Io.Database.ProjectEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Io.Database.PipelineEntity", b =>
                {
                    b.Navigation("Builds");

                    b.Navigation("UpstreamBuild");
                });

            modelBuilder.Entity("Io.Database.RunnerEntity", b =>
                {
                    b.Navigation("Builds");
                });
#pragma warning restore 612, 618
        }
    }
}
