// <auto-generated />
using System;
using Io.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Io.Migrations
{
    [DbContext(typeof(IoDbContext))]
    [Migration("20220729045728_ExcludeDownstreamFromHealth")]
    partial class ExcludeDownstreamFromHealth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Io.Database.BuildEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("AllowFailure")
                        .HasColumnType("boolean");

                    b.Property<string>("ArtifactsFilename")
                        .HasColumnType("text");

                    b.Property<long?>("ArtifactsSize")
                        .HasColumnType("bigint");

                    b.Property<Instant?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DownstreamPipelineId")
                        .HasColumnType("bigint");

                    b.Property<long?>("Duration")
                        .HasColumnType("bigint");

                    b.Property<Instant?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastUpdatedByWebhookEventId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Manual")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("PipelineId")
                        .HasColumnType("bigint");

                    b.Property<string[]>("RanWithTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<long?>("RunnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Stage")
                        .HasColumnType("text");

                    b.Property<Instant?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("When")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DownstreamPipelineId")
                        .IsUnique();

                    b.HasIndex("PipelineId");

                    b.HasIndex("RunnerId");

                    b.HasIndex("UserId");

                    b.ToTable("Builds");
                });

            modelBuilder.Entity("Io.Database.BuildEstimations", b =>
                {
                    b.Property<long>("BuildId")
                        .HasColumnType("bigint");

                    b.Property<Instant?>("EstimatedFinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasIndex("BuildId")
                        .IsUnique();

                    b.ToView("BuildEstimations");
                });

            modelBuilder.Entity("Io.Database.BuildStatusChangeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("NewStatus")
                        .HasColumnType("text");

                    b.Property<string>("OldStatus")
                        .HasColumnType("text");

                    b.Property<Instant?>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuildId");

                    b.ToTable("BuildStatusChanges");
                });

            modelBuilder.Entity("Io.Database.CommitEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AuthorEmail")
                        .HasColumnType("text");

                    b.Property<string>("AuthorName")
                        .HasColumnType("text");

                    b.Property<long>("LastUpdatedByWebhookEventId")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Timestamp")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Commits");
                });

            modelBuilder.Entity("Io.Database.Entities.TestEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AutomationInstance")
                        .HasColumnType("text");

                    b.Property<long>("BuildId")
                        .HasColumnType("bigint");

                    b.Property<Instant?>("DateCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("DateFinishedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("DateStartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DurationEstimationHash")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasComputedColumnSql("\"FullName\" || ':' || \"Platform\"", true);

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("GauntletInstance")
                        .HasColumnType("text");

                    b.Property<bool?>("IsGauntlet")
                        .HasColumnType("boolean");

                    b.Property<string>("LookupId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasComputedColumnSql("\"BuildId\"::text || ':' || \"FullName\" || ':' || \"Platform\" || ':' || \"GauntletInstance\"", true);

                    b.Property<string>("Platform")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BuildId");

                    b.HasIndex("LookupId")
                        .IsUnique();

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("Io.Database.Entities.TestLogEntity", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("TestId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("TestLogs");
                });

            modelBuilder.Entity("Io.Database.Entities.UtilizationInvalidationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Instant?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("UtilizationInvalidation");
                });

            modelBuilder.Entity("Io.Database.Entities.UtilizationMinuteEntity", b =>
                {
                    b.Property<Instant?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RunnerTag")
                        .HasColumnType("text");

                    b.Property<long?>("Created")
                        .HasColumnType("bigint");

                    b.Property<long?>("Pending")
                        .HasColumnType("bigint");

                    b.Property<long?>("Running")
                        .HasColumnType("bigint");

                    b.HasKey("Timestamp", "RunnerTag");

                    b.HasIndex("RunnerTag");

                    b.HasIndex("Timestamp");

                    b.ToTable("UtilizationMinutes");
                });

            modelBuilder.Entity("Io.Database.MergeRequestEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("InternalId")
                        .HasColumnType("bigint");

                    b.Property<long>("LastUpdatedByWebhookEventId")
                        .HasColumnType("bigint");

                    b.Property<string>("MergeStatus")
                        .HasColumnType("text");

                    b.Property<string>("SourceBranch")
                        .HasColumnType("text");

                    b.Property<long?>("SourceProjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("TargetBranch")
                        .HasColumnType("text");

                    b.Property<long?>("TargetProjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MergeRequests");
                });

            modelBuilder.Entity("Io.Database.PipelineEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CommitId")
                        .HasColumnType("text");

                    b.Property<Instant?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailedStatus")
                        .HasColumnType("text");

                    b.Property<long?>("Duration")
                        .HasColumnType("bigint");

                    b.Property<Instant?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastUpdatedByWebhookEventId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MergeRequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("PreviousSha")
                        .HasColumnType("text");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<long?>("QueuedDuration")
                        .HasColumnType("bigint");

                    b.Property<string>("Ref")
                        .HasColumnType("text");

                    b.Property<string>("Sha")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string[]>("Stages")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<bool?>("Tag")
                        .HasColumnType("boolean");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CommitId");

                    b.HasIndex("MergeRequestId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Pipelines");
                });

            modelBuilder.Entity("Io.Database.PipelineEstimations", b =>
                {
                    b.Property<Instant?>("EstimatedFinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PipelineId")
                        .HasColumnType("bigint");

                    b.HasIndex("PipelineId")
                        .IsUnique();

                    b.ToView("PipelineEstimations");
                });

            modelBuilder.Entity("Io.Database.ProjectEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("DefaultBranch")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GitHttpUrl")
                        .HasColumnType("text");

                    b.Property<string>("GitSshUrl")
                        .HasColumnType("text");

                    b.Property<long>("LastUpdatedByWebhookEventId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Namespace")
                        .HasColumnType("text");

                    b.Property<string>("PathWithNamespace")
                        .HasColumnType("text");

                    b.Property<long?>("VisibilityLevel")
                        .HasColumnType("bigint");

                    b.Property<string>("WebUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Io.Database.RunnerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool?>("IsShared")
                        .HasColumnType("boolean");

                    b.Property<long>("LastUpdatedByWebhookEventId")
                        .HasColumnType("bigint");

                    b.Property<string>("RunnerType")
                        .HasColumnType("text");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Runners");
                });

            modelBuilder.Entity("Io.Database.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<long>("LastUpdatedByWebhookEventId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Io.Database.Views.DesiredCapacityCalculations", b =>
                {
                    b.Property<double>("DesiredCapacity")
                        .HasColumnType("double precision");

                    b.Property<double>("Percentile")
                        .HasColumnType("double precision");

                    b.Property<string>("RunnerTag")
                        .HasColumnType("text");

                    b.ToView("DesiredCapacityCalculations");
                });

            modelBuilder.Entity("Io.Database.Views.ProjectHealths", b =>
                {
                    b.Property<string>("DefaultBranch")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("PipelineId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("Sha")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("WebUrl")
                        .HasColumnType("text");

                    b.HasIndex("PipelineId")
                        .IsUnique();

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToView("ProjectHealths");
                });

            modelBuilder.Entity("Io.Database.Views.TimestampedBuilds", b =>
                {
                    b.Property<long>("BuildId")
                        .HasColumnType("bigint");

                    b.Property<Instant?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("PendingAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string[]>("RanWithTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Instant?>("RunningAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasIndex("BuildId")
                        .IsUnique();

                    b.ToView("TimestampedBuilds");
                });

            modelBuilder.Entity("Io.Database.WebhookEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Instant?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("Data")
                        .HasColumnType("json");

                    b.Property<bool?>("Done")
                        .HasColumnType("boolean");

                    b.Property<string>("ObjectKind")
                        .HasColumnType("text");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<Instant?>("ReservationTimeout")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReservedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WebhookEvents");
                });

            modelBuilder.Entity("Io.Database.BuildEntity", b =>
                {
                    b.HasOne("Io.Database.PipelineEntity", "DownstreamPipeline")
                        .WithOne("UpstreamBuild")
                        .HasForeignKey("Io.Database.BuildEntity", "DownstreamPipelineId");

                    b.HasOne("Io.Database.PipelineEntity", "Pipeline")
                        .WithMany("Builds")
                        .HasForeignKey("PipelineId");

                    b.HasOne("Io.Database.RunnerEntity", "Runner")
                        .WithMany("Builds")
                        .HasForeignKey("RunnerId");

                    b.HasOne("Io.Database.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("DownstreamPipeline");

                    b.Navigation("Pipeline");

                    b.Navigation("Runner");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Io.Database.BuildEstimations", b =>
                {
                    b.HasOne("Io.Database.BuildEntity", "Build")
                        .WithOne()
                        .HasForeignKey("Io.Database.BuildEstimations", "BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Build");
                });

            modelBuilder.Entity("Io.Database.BuildStatusChangeEntity", b =>
                {
                    b.HasOne("Io.Database.BuildEntity", "Build")
                        .WithMany()
                        .HasForeignKey("BuildId");

                    b.Navigation("Build");
                });

            modelBuilder.Entity("Io.Database.Entities.TestEntity", b =>
                {
                    b.HasOne("Io.Database.BuildEntity", "Build")
                        .WithMany()
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Build");
                });

            modelBuilder.Entity("Io.Database.Entities.TestLogEntity", b =>
                {
                    b.HasOne("Io.Database.Entities.TestEntity", "Test")
                        .WithMany()
                        .HasForeignKey("TestId");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Io.Database.PipelineEntity", b =>
                {
                    b.HasOne("Io.Database.CommitEntity", "Commit")
                        .WithMany()
                        .HasForeignKey("CommitId");

                    b.HasOne("Io.Database.MergeRequestEntity", "MergeRequest")
                        .WithMany()
                        .HasForeignKey("MergeRequestId");

                    b.HasOne("Io.Database.ProjectEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("Io.Database.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Commit");

                    b.Navigation("MergeRequest");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Io.Database.PipelineEstimations", b =>
                {
                    b.HasOne("Io.Database.PipelineEntity", "Pipeline")
                        .WithOne()
                        .HasForeignKey("Io.Database.PipelineEstimations", "PipelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pipeline");
                });

            modelBuilder.Entity("Io.Database.Views.ProjectHealths", b =>
                {
                    b.HasOne("Io.Database.PipelineEntity", "Pipeline")
                        .WithOne()
                        .HasForeignKey("Io.Database.Views.ProjectHealths", "PipelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Io.Database.ProjectEntity", "Project")
                        .WithOne()
                        .HasForeignKey("Io.Database.Views.ProjectHealths", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pipeline");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Io.Database.Views.TimestampedBuilds", b =>
                {
                    b.HasOne("Io.Database.BuildEntity", "Build")
                        .WithOne()
                        .HasForeignKey("Io.Database.Views.TimestampedBuilds", "BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Build");
                });

            modelBuilder.Entity("Io.Database.PipelineEntity", b =>
                {
                    b.Navigation("Builds");

                    b.Navigation("UpstreamBuild");
                });

            modelBuilder.Entity("Io.Database.RunnerEntity", b =>
                {
                    b.Navigation("Builds");
                });
#pragma warning restore 612, 618
        }
    }
}
