namespace Redpoint.OpenGE.Component.PreprocessorCache.Tests
{
    using Redpoint.OpenGE.Component.PreprocessorCache.DependencyResolution;
    using Redpoint.OpenGE.Component.PreprocessorCache.DirectiveScanner;
    using Redpoint.OpenGE.Component.PreprocessorCache.Filesystem;
    using Redpoint.OpenGE.Protocol;

    public class ResolverTests
    {
        [SkippableFact]
        public async Task ResolvePchInclude()
        {
            var enginePath = @"C:\UnrealEngine\5.2\Engine\Source";
            Skip.IfNot(Directory.Exists(enginePath), "Requires UE5 to be present on disk.");
            var path = @"C:\Work\internal\EOS_OSB\EOS_OSB\Intermediate\Build\Win64\x64\ExampleOSSEditor\DebugGame\Engine\SharedPCH.Engine.NonOptimized.ShadowErrors.h";
            Skip.IfNot(File.Exists(path), "Requires project to be present on disk.");

            var includes = new[]
            {
                @".",
                @"..\Plugins\Online\OnlineSubsystem\Intermediate\Build\Win64\UnrealEditor\Inc\OnlineSubsystem\UHT",
                @"..\Plugins\Online\OnlineSubsystem\Source",
                @"..\Plugins\Online\OnlineSubsystem\Source\Public",
                @"..\Plugins\Online\OnlineSubsystem",
                @"Runtime\Json\Public",
                @"Runtime",
                @"Runtime\TraceLog\Public",
                @"Runtime\Core\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\CoreOnline\UHT",
                @"Runtime\CoreOnline\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\CoreUObject\UHT",
                @"Runtime\CoreUObject\Public",
                @"..\Plugins\Online\OnlineBase\Source\Public",
                @"..\Plugins\Online\OnlineBase",
                @"Runtime\Sockets\Public",
                @"Runtime\Net\Common\Public",
                @"Runtime\Net",
                @"Runtime\SignalProcessing\Public",
                @"ThirdParty\Intel",
                @"C:\Work\internal\EOS_OSB\EOS_OSB\Source",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\Engine\UHT",
                @"..\Shaders\Shared",
                @"Runtime\Engine\Classes",
                @"Runtime\Engine\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\NetCore\UHT",
                @"Runtime\Net\Core\Classes",
                @"Runtime\Net\Core\Public",
                @"Runtime\ApplicationCore\Public",
                @"Runtime\RHI\Public",
                @"Runtime\ImageCore\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\JsonUtilities\UHT",
                @"Runtime\JsonUtilities\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\SlateCore\UHT",
                @"Runtime\SlateCore\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\InputCore\UHT",
                @"Runtime\InputCore\Classes",
                @"Runtime\InputCore\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\Slate\UHT",
                @"Runtime\Slate\Public",
                @"Runtime\ImageWrapper\Public",
                @"ThirdParty",
                @"Runtime\Messaging\Public",
                @"Runtime\MessagingCommon\Public",
                @"Runtime\RenderCore\Public",
                @"Runtime\Analytics\AnalyticsET\Public",
                @"Runtime\Analytics",
                @"Runtime\Analytics\Analytics\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AssetRegistry\UHT",
                @"Runtime\AssetRegistry\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\EngineMessages\UHT",
                @"Runtime\EngineMessages\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\EngineSettings\UHT",
                @"Runtime\EngineSettings\Classes",
                @"Runtime\EngineSettings\Public",
                @"Runtime\SynthBenchmark\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\Renderer\UHT",
                @"Runtime\Renderer\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\GameplayTags\UHT",
                @"Runtime\GameplayTags\Classes",
                @"Runtime\GameplayTags\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\DeveloperSettings\UHT",
                @"Runtime\DeveloperSettings\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\PacketHandler\UHT",
                @"Runtime\PacketHandlers\PacketHandler\Classes",
                @"Runtime\PacketHandlers\PacketHandler\Public",
                @"Runtime\PacketHandlers",
                @"Runtime\PacketHandlers\ReliabilityHandlerComponent\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AudioPlatformConfiguration\UHT",
                @"Runtime\AudioPlatformConfiguration\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\MeshDescription\UHT",
                @"Runtime\MeshDescription\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\StaticMeshDescription\UHT",
                @"Runtime\StaticMeshDescription\Public",
                @"Runtime\SkeletalMeshDescription\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AnimationCore\UHT",
                @"Runtime\AnimationCore\Public",
                @"Runtime\PakFile\Public",
                @"Runtime\RSA\Public",
                @"Runtime\NetworkReplayStreaming\NetworkReplayStreaming\Public",
                @"Runtime\NetworkReplayStreaming",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\PhysicsCore\UHT",
                @"Runtime\PhysicsCore\Public",
                @"Runtime\Experimental\ChaosCore\Public",
                @"Runtime\Experimental",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\Chaos\UHT",
                @"Runtime\Experimental\Chaos\Public",
                @"Runtime\Experimental\Voronoi\Public",
                @"Runtime\GeometryCore\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AudioExtensions\UHT",
                @"Runtime\AudioExtensions\Public",
                @"Runtime\AudioMixerCore\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AudioLinkCore\UHT",
                @"Runtime\AudioLink\AudioLinkCore\Public",
                @"Runtime\AudioLink",
                @"Runtime\Networking\Public",
                @"Developer\TextureBuildUtilities\Public",
                @"Developer",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\UnrealEd\UHT",
                @"Programs\UnrealLightmass\Public",
                @"Editor\UnrealEd\Classes",
                @"Editor\UnrealEd\Public",
                @"Editor",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AssetDefinition\UHT",
                @"Editor\AssetDefinition\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\EditorSubsystem\UHT",
                @"Editor\EditorSubsystem\Public",
                @"Developer\DirectoryWatcher\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\Documentation\UHT",
                @"Editor\Documentation\Public",
                @"Editor\MainFrame\Public",
                @"Runtime\Projects\Public",
                @"Runtime\SandboxFile\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\EditorFramework\UHT",
                @"Editor\EditorFramework\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\InteractiveToolsFramework\UHT",
                @"Runtime\InteractiveToolsFramework\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\TypedElementFramework\UHT",
                @"Runtime\TypedElementFramework\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\TypedElementRuntime\UHT",
                @"Runtime\TypedElementRuntime\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\SourceControl\UHT",
                @"Developer\SourceControl\Public",
                @"Developer\UncontrolledChangelists\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\UnrealEdMessages\UHT",
                @"Editor\UnrealEdMessages\Classes",
                @"Editor\UnrealEdMessages\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\GameplayDebugger\UHT",
                @"Runtime\GameplayDebugger\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\BlueprintGraph\UHT",
                @"Editor\BlueprintGraph\Classes",
                @"Editor\BlueprintGraph\Public",
                @"Runtime\Online\HTTP\Public",
                @"Runtime\Online",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\FunctionalTesting\UHT",
                @"Developer\FunctionalTesting\Classes",
                @"Developer\FunctionalTesting\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AutomationController\UHT",
                @"Developer\AutomationController\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AutomationTest\UHT",
                @"Runtime\AutomationTest\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\Localization\UHT",
                @"Developer\Localization\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AudioEditor\UHT",
                @"Editor\AudioEditor\Classes",
                @"Editor\AudioEditor\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AudioMixer\UHT",
                @"Runtime\AudioMixer\Classes",
                @"Runtime\AudioMixer\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AudioLinkEngine\UHT",
                @"Runtime\AudioLink\AudioLinkEngine\Public",
                @"Developer\TargetPlatform\Public",
                @"Developer\TextureFormat\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\LevelEditor\UHT",
                @"Editor\LevelEditor\Public",
                @"Developer\Settings\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\HeadMountedDisplay\UHT",
                @"Runtime\HeadMountedDisplay\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\VREditor\UHT",
                @"Editor\VREditor",
                @"Editor\VREditor\Public",
                @"Editor\CommonMenuExtensions\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\Landscape\UHT",
                @"Runtime\Landscape\Classes",
                @"Runtime\Landscape\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\PropertyEditor\UHT",
                @"Editor\PropertyEditor\Public",
                @"Editor\ActorPickerMode\Public",
                @"Editor\SceneDepthPickerMode\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\EditorConfig\UHT",
                @"Editor\EditorConfig\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\DetailCustomizations\UHT",
                @"Editor\DetailCustomizations\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\ClassViewer\UHT",
                @"Editor\ClassViewer\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\GraphEditor\UHT",
                @"Editor\GraphEditor\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\StructViewer\UHT",
                @"Editor\StructViewer\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\ContentBrowser\UHT",
                @"Editor\ContentBrowser\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AssetTools\UHT",
                @"Developer\AssetTools\Public",
                @"Developer\Merge\Public",
                @"Developer\CollectionManager\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\ContentBrowserData\UHT",
                @"Editor\ContentBrowserData\Public",
                @"ThirdParty\libSampleRate\Public",
                @"Runtime\NetworkFileSystem\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\UMG\UHT",
                @"Runtime\UMG\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\MovieScene\UHT",
                @"Runtime\MovieScene\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\TimeManagement\UHT",
                @"Runtime\TimeManagement\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\MovieSceneTracks\UHT",
                @"Runtime\MovieSceneTracks\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\Constraints\UHT",
                @"Runtime\Experimental\Animation\Constraints\Public",
                @"Runtime\Experimental\Animation",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\PropertyPath\UHT",
                @"Runtime\PropertyPath\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\NavigationSystem\UHT",
                @"Runtime\NavigationSystem\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\GeometryCollectionEngine\UHT",
                @"Runtime\Experimental\GeometryCollectionEngine\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\MSQS\UHT",
                @"Runtime\MaterialShaderQualitySettings\Classes",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\FieldSystemEngine\UHT",
                @"Runtime\Experimental\FieldSystem\Source\FieldSystemEngine\Public",
                @"Runtime\Experimental\FieldSystem\Source",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\ChaosSolverEngine\UHT",
                @"Runtime\Experimental\ChaosSolverEngine\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\DataflowCore\UHT",
                @"Runtime\Experimental\Dataflow\Core\Public",
                @"Runtime\Experimental\Dataflow",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\DataflowEngine\UHT",
                @"Runtime\Experimental\Dataflow\Engine\Public",
                @"Developer\MeshBuilder\Public",
                @"Runtime\MeshUtilitiesCommon\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\ToolMenusEditor\UHT",
                @"Editor\ToolMenusEditor\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\ToolMenus\UHT",
                @"Developer\ToolMenus\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\StatusBar\UHT",
                @"Editor\StatusBar\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\InterchangeCore\UHT",
                @"Runtime\Interchange\Core\Public",
                @"Runtime\Interchange",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\InterchangeEngine\UHT",
                @"Runtime\Interchange\Engine\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\DeveloperToolSettings\UHT",
                @"Developer\DeveloperToolSettings\Classes",
                @"Developer\DeveloperToolSettings\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\SubobjectDataInterface\UHT",
                @"Editor\SubobjectDataInterface\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\SubobjectEditor\UHT",
                @"Editor\SubobjectEditor\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\Kismet\UHT",
                @"Editor\Kismet\Classes",
                @"Editor\Kismet\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\PhysicsUtilities\UHT",
                @"Developer\PhysicsUtilities\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\ToolWidgets\UHT",
                @"Developer\ToolWidgets\Public",
                @"Runtime\Windows",
                @"Editor\AssetTagsEditor\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AddContentDialog\UHT",
                @"Editor\AddContentDialog\Public",
                @"Developer\MeshUtilities\Public",
                @"Developer\MeshMergeUtilities\Public",
                @"Developer\HierarchicalLODUtilities\Public",
                @"Developer\MeshReductionInterface\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\SkeletalMeshEditor\UHT",
                @"Editor\SkeletalMeshEditor\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\Persona\UHT",
                @"Editor\Persona\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\SkeletonEditor\UHT",
                @"Editor\SkeletonEditor\Public",
                @"Developer\AnimationWidgets\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AnimationEditor\UHT",
                @"Editor\AnimationEditor\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AdvancedPreviewScene\UHT",
                @"Editor\AdvancedPreviewScene\Public",
                @"Editor\KismetCompiler\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\GameplayTasks\UHT",
                @"Runtime\GameplayTasks\Classes",
                @"Runtime\GameplayTasks\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AIModule\UHT",
                @"Runtime\AIModule\Public",
                @"Runtime\AIModule\Classes",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\ClothSysRuntimeIntrfc\UHT",
                @"Runtime\ClothingSystemRuntimeInterface\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\IrisCore\UHT",
                @"Runtime\Experimental\Iris\Core\Public",
                @"Runtime\Experimental\Iris",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\MovieSceneCapture\UHT",
                @"Runtime\MovieSceneCapture\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AnimationDataController\UHT",
                @"Developer\AnimationDataController\Public",
                @"C:\Work\internal\EOS_OSB\EOS_OSB\Intermediate\Build\Win64\UnrealEditor\Inc\ExampleOSS\UHT",
                @"..\Plugins\Online\OnlineSubsystemUtils\Intermediate\Build\Win64\UnrealEditor\Inc\OnlineSubsystemUtils\UHT",
                @"..\Plugins\Online\OnlineSubsystemUtils\Source\OnlineSubsystemUtils\Classes",
                @"..\Plugins\Online\OnlineSubsystemUtils\Source\OnlineSubsystemUtils\Public",
                @"..\Plugins\Online\OnlineSubsystemUtils\Source",
                @"..\Plugins\Online\VoiceChat\VoiceChat\Source\Public",
                @"..\Plugins\Online\VoiceChat\VoiceChat",
                @"ThirdParty\mimalloc\include",
                @"ThirdParty\LibTiff\Source\Win64",
                @"ThirdParty\LibTiff\Source",
                @"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\INCLUDE",
                @"C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt",
                @"C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared",
                @"C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um",
                @"C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt",
            }.Select(x => Path.GetFullPath(Path.IsPathRooted(x) ? x : Path.Combine(enginePath, x))).ToArray();
            var globalDefinitions = new Dictionary<string, string>
            {
                { "_CRT_STDIO_LEGACY_WIDE_SPECIFIERS", "1" },
                { "_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS", "1" },
                { "_WINDLL", "1" },
                { "_DISABLE_EXTENDED_ALIGNED_STORAGE", "1" },
                { "PLATFORM_EXCEPTIONS_DISABLED", "0" },
            };

            var resolver = new DefaultPreprocessorResolver(new GenericInMemoryFilesystemExistenceProvider());

            // @note: We just want to make sure this does not throw an exception.
            var result = await resolver.ResolveAsync(
                new NonCachingPreprocessorScanner(),
                path,
                Array.Empty<string>(),
                includes,
                globalDefinitions,
                DateTimeOffset.UtcNow.Ticks,
                new CompilerArchitype
                {
                    Msvc = new MsvcCompiler
                    {
                        CppLanguageVersion = 201703 /* C++ 17 */,
                        MsvcVersion = 1935 /* 2022 17.5 */,
                        MsvcFullVersion = 193599999 /* Latest 2022 17.5 */,
                        CLanguageVersion = 201710 /* C 17 */,
                    },
                    TargetPlatformNumericDefines =
                    {
                        { "_WIN32", 1 },
                        { "_WIN64", 1 },
                        { "_WIN32_WINNT", 0x0601 /* Windows 7 */ },
                        { "_WIN32_WINNT_WIN10_TH2", 0x0A01 },
                        { "_WIN32_WINNT_WIN10_RS1", 0x0A02 },
                        { "_WIN32_WINNT_WIN10_RS2", 0x0A03 },
                        { "_WIN32_WINNT_WIN10_RS3", 0x0A04 },
                        { "_WIN32_WINNT_WIN10_RS4", 0x0A05 },
                        { "_NT_TARGET_VERSION_WIN10_RS4", 0x0A05 },
                        { "_WIN32_WINNT_WIN10_RS5", 0x0A06 },
                        { "_M_X64", 1 },
                        { "_VCRT_COMPILER_PREPROCESSOR", 1 },
                        /*
                         * Some undocumented define that the Windows headers rely on 
                         * for Compiled Hybrid Portable Executable (CHPE) support, 
                         * which is for x86 binaries that include ARM code. This
                         * undocumented feature has since been replaced with ARM64EC,
                         * so we don't need to actually support this; we just need the
                         * define so the headers work.
                         */
                        { "_M_HYBRID", 0 },
                    }
                },
                CancellationToken.None);
            Assert.True(result.DependsOnPaths.Count >= 2, "Expected at least two paths to be depended on.");
        }

        [SkippableFact]
        public async Task ResolveDownstreamConsumerOfPchInclude()
        {
            var enginePath = @"C:\UnrealEngine\5.2\Engine\Source";
            Skip.IfNot(Directory.Exists(enginePath), "Requires UE5 to be present on disk.");
            var pchPath = @"C:\Work\internal\EOS_OSB\EOS_OSB\Intermediate\Build\Win64\x64\ExampleOSSEditor\DebugGame\Engine\SharedPCH.Engine.NonOptimized.ShadowErrors.h";
            Skip.IfNot(File.Exists(pchPath), "Requires project to be present on disk.");
            Skip.IfNot(File.Exists(@"C:\Work\internal\EOS_OSB\EOS_OSB\Intermediate\Build\Win64\x64\UnrealEditor\DebugGame\ExampleOSS\Module.ExampleOSS.1_of_3.cpp"), "Requires project to be present on disk.");
            Skip.IfNot(File.Exists(@"C:\Work\internal\EOS_OSB\EOS_OSB\Intermediate\Build\Win64\x64\UnrealEditor\DebugGame\ExampleOSS\Definitions.ExampleOSS.h"), "Requires project to be present on disk.");

            var includes = new[]
            {
                @".",
                @"..\Plugins\Online\OnlineSubsystem\Intermediate\Build\Win64\UnrealEditor\Inc\OnlineSubsystem\UHT",
                @"..\Plugins\Online\OnlineSubsystem\Source",
                @"..\Plugins\Online\OnlineSubsystem\Source\Public",
                @"..\Plugins\Online\OnlineSubsystem",
                @"Runtime\Json\Public",
                @"Runtime",
                @"Runtime\TraceLog\Public",
                @"Runtime\Core\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\CoreOnline\UHT",
                @"Runtime\CoreOnline\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\CoreUObject\UHT",
                @"Runtime\CoreUObject\Public",
                @"..\Plugins\Online\OnlineBase\Source\Public",
                @"..\Plugins\Online\OnlineBase",
                @"Runtime\Sockets\Public",
                @"Runtime\Net\Common\Public",
                @"Runtime\Net",
                @"Runtime\SignalProcessing\Public",
                @"ThirdParty\Intel",
                @"C:\Work\internal\EOS_OSB\EOS_OSB\Source",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\Engine\UHT",
                @"..\Shaders\Shared",
                @"Runtime\Engine\Classes",
                @"Runtime\Engine\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\NetCore\UHT",
                @"Runtime\Net\Core\Classes",
                @"Runtime\Net\Core\Public",
                @"Runtime\ApplicationCore\Public",
                @"Runtime\RHI\Public",
                @"Runtime\ImageCore\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\JsonUtilities\UHT",
                @"Runtime\JsonUtilities\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\SlateCore\UHT",
                @"Runtime\SlateCore\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\InputCore\UHT",
                @"Runtime\InputCore\Classes",
                @"Runtime\InputCore\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\Slate\UHT",
                @"Runtime\Slate\Public",
                @"Runtime\ImageWrapper\Public",
                @"ThirdParty",
                @"Runtime\Messaging\Public",
                @"Runtime\MessagingCommon\Public",
                @"Runtime\RenderCore\Public",
                @"Runtime\Analytics\AnalyticsET\Public",
                @"Runtime\Analytics",
                @"Runtime\Analytics\Analytics\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AssetRegistry\UHT",
                @"Runtime\AssetRegistry\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\EngineMessages\UHT",
                @"Runtime\EngineMessages\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\EngineSettings\UHT",
                @"Runtime\EngineSettings\Classes",
                @"Runtime\EngineSettings\Public",
                @"Runtime\SynthBenchmark\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\Renderer\UHT",
                @"Runtime\Renderer\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\GameplayTags\UHT",
                @"Runtime\GameplayTags\Classes",
                @"Runtime\GameplayTags\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\DeveloperSettings\UHT",
                @"Runtime\DeveloperSettings\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\PacketHandler\UHT",
                @"Runtime\PacketHandlers\PacketHandler\Classes",
                @"Runtime\PacketHandlers\PacketHandler\Public",
                @"Runtime\PacketHandlers",
                @"Runtime\PacketHandlers\ReliabilityHandlerComponent\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AudioPlatformConfiguration\UHT",
                @"Runtime\AudioPlatformConfiguration\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\MeshDescription\UHT",
                @"Runtime\MeshDescription\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\StaticMeshDescription\UHT",
                @"Runtime\StaticMeshDescription\Public",
                @"Runtime\SkeletalMeshDescription\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AnimationCore\UHT",
                @"Runtime\AnimationCore\Public",
                @"Runtime\PakFile\Public",
                @"Runtime\RSA\Public",
                @"Runtime\NetworkReplayStreaming\NetworkReplayStreaming\Public",
                @"Runtime\NetworkReplayStreaming",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\PhysicsCore\UHT",
                @"Runtime\PhysicsCore\Public",
                @"Runtime\Experimental\ChaosCore\Public",
                @"Runtime\Experimental",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\Chaos\UHT",
                @"Runtime\Experimental\Chaos\Public",
                @"Runtime\Experimental\Voronoi\Public",
                @"Runtime\GeometryCore\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AudioExtensions\UHT",
                @"Runtime\AudioExtensions\Public",
                @"Runtime\AudioMixerCore\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AudioLinkCore\UHT",
                @"Runtime\AudioLink\AudioLinkCore\Public",
                @"Runtime\AudioLink",
                @"Runtime\Networking\Public",
                @"Developer\TextureBuildUtilities\Public",
                @"Developer",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\UnrealEd\UHT",
                @"Programs\UnrealLightmass\Public",
                @"Editor\UnrealEd\Classes",
                @"Editor\UnrealEd\Public",
                @"Editor",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AssetDefinition\UHT",
                @"Editor\AssetDefinition\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\EditorSubsystem\UHT",
                @"Editor\EditorSubsystem\Public",
                @"Developer\DirectoryWatcher\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\Documentation\UHT",
                @"Editor\Documentation\Public",
                @"Editor\MainFrame\Public",
                @"Runtime\Projects\Public",
                @"Runtime\SandboxFile\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\EditorFramework\UHT",
                @"Editor\EditorFramework\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\InteractiveToolsFramework\UHT",
                @"Runtime\InteractiveToolsFramework\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\TypedElementFramework\UHT",
                @"Runtime\TypedElementFramework\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\TypedElementRuntime\UHT",
                @"Runtime\TypedElementRuntime\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\SourceControl\UHT",
                @"Developer\SourceControl\Public",
                @"Developer\UncontrolledChangelists\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\UnrealEdMessages\UHT",
                @"Editor\UnrealEdMessages\Classes",
                @"Editor\UnrealEdMessages\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\GameplayDebugger\UHT",
                @"Runtime\GameplayDebugger\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\BlueprintGraph\UHT",
                @"Editor\BlueprintGraph\Classes",
                @"Editor\BlueprintGraph\Public",
                @"Runtime\Online\HTTP\Public",
                @"Runtime\Online",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\FunctionalTesting\UHT",
                @"Developer\FunctionalTesting\Classes",
                @"Developer\FunctionalTesting\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AutomationController\UHT",
                @"Developer\AutomationController\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AutomationTest\UHT",
                @"Runtime\AutomationTest\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\Localization\UHT",
                @"Developer\Localization\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AudioEditor\UHT",
                @"Editor\AudioEditor\Classes",
                @"Editor\AudioEditor\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AudioMixer\UHT",
                @"Runtime\AudioMixer\Classes",
                @"Runtime\AudioMixer\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AudioLinkEngine\UHT",
                @"Runtime\AudioLink\AudioLinkEngine\Public",
                @"Developer\TargetPlatform\Public",
                @"Developer\TextureFormat\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\LevelEditor\UHT",
                @"Editor\LevelEditor\Public",
                @"Developer\Settings\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\HeadMountedDisplay\UHT",
                @"Runtime\HeadMountedDisplay\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\VREditor\UHT",
                @"Editor\VREditor",
                @"Editor\VREditor\Public",
                @"Editor\CommonMenuExtensions\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\Landscape\UHT",
                @"Runtime\Landscape\Classes",
                @"Runtime\Landscape\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\PropertyEditor\UHT",
                @"Editor\PropertyEditor\Public",
                @"Editor\ActorPickerMode\Public",
                @"Editor\SceneDepthPickerMode\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\EditorConfig\UHT",
                @"Editor\EditorConfig\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\DetailCustomizations\UHT",
                @"Editor\DetailCustomizations\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\ClassViewer\UHT",
                @"Editor\ClassViewer\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\GraphEditor\UHT",
                @"Editor\GraphEditor\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\StructViewer\UHT",
                @"Editor\StructViewer\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\ContentBrowser\UHT",
                @"Editor\ContentBrowser\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AssetTools\UHT",
                @"Developer\AssetTools\Public",
                @"Developer\Merge\Public",
                @"Developer\CollectionManager\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\ContentBrowserData\UHT",
                @"Editor\ContentBrowserData\Public",
                @"ThirdParty\libSampleRate\Public",
                @"Runtime\NetworkFileSystem\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\UMG\UHT",
                @"Runtime\UMG\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\MovieScene\UHT",
                @"Runtime\MovieScene\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\TimeManagement\UHT",
                @"Runtime\TimeManagement\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\MovieSceneTracks\UHT",
                @"Runtime\MovieSceneTracks\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\Constraints\UHT",
                @"Runtime\Experimental\Animation\Constraints\Public",
                @"Runtime\Experimental\Animation",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\PropertyPath\UHT",
                @"Runtime\PropertyPath\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\NavigationSystem\UHT",
                @"Runtime\NavigationSystem\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\GeometryCollectionEngine\UHT",
                @"Runtime\Experimental\GeometryCollectionEngine\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\MSQS\UHT",
                @"Runtime\MaterialShaderQualitySettings\Classes",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\FieldSystemEngine\UHT",
                @"Runtime\Experimental\FieldSystem\Source\FieldSystemEngine\Public",
                @"Runtime\Experimental\FieldSystem\Source",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\ChaosSolverEngine\UHT",
                @"Runtime\Experimental\ChaosSolverEngine\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\DataflowCore\UHT",
                @"Runtime\Experimental\Dataflow\Core\Public",
                @"Runtime\Experimental\Dataflow",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\DataflowEngine\UHT",
                @"Runtime\Experimental\Dataflow\Engine\Public",
                @"Developer\MeshBuilder\Public",
                @"Runtime\MeshUtilitiesCommon\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\ToolMenusEditor\UHT",
                @"Editor\ToolMenusEditor\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\ToolMenus\UHT",
                @"Developer\ToolMenus\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\StatusBar\UHT",
                @"Editor\StatusBar\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\InterchangeCore\UHT",
                @"Runtime\Interchange\Core\Public",
                @"Runtime\Interchange",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\InterchangeEngine\UHT",
                @"Runtime\Interchange\Engine\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\DeveloperToolSettings\UHT",
                @"Developer\DeveloperToolSettings\Classes",
                @"Developer\DeveloperToolSettings\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\SubobjectDataInterface\UHT",
                @"Editor\SubobjectDataInterface\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\SubobjectEditor\UHT",
                @"Editor\SubobjectEditor\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\Kismet\UHT",
                @"Editor\Kismet\Classes",
                @"Editor\Kismet\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\PhysicsUtilities\UHT",
                @"Developer\PhysicsUtilities\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\ToolWidgets\UHT",
                @"Developer\ToolWidgets\Public",
                @"Runtime\Windows",
                @"Editor\AssetTagsEditor\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AddContentDialog\UHT",
                @"Editor\AddContentDialog\Public",
                @"Developer\MeshUtilities\Public",
                @"Developer\MeshMergeUtilities\Public",
                @"Developer\HierarchicalLODUtilities\Public",
                @"Developer\MeshReductionInterface\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\SkeletalMeshEditor\UHT",
                @"Editor\SkeletalMeshEditor\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\Persona\UHT",
                @"Editor\Persona\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\SkeletonEditor\UHT",
                @"Editor\SkeletonEditor\Public",
                @"Developer\AnimationWidgets\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AnimationEditor\UHT",
                @"Editor\AnimationEditor\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AdvancedPreviewScene\UHT",
                @"Editor\AdvancedPreviewScene\Public",
                @"Editor\KismetCompiler\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\GameplayTasks\UHT",
                @"Runtime\GameplayTasks\Classes",
                @"Runtime\GameplayTasks\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AIModule\UHT",
                @"Runtime\AIModule\Public",
                @"Runtime\AIModule\Classes",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\ClothSysRuntimeIntrfc\UHT",
                @"Runtime\ClothingSystemRuntimeInterface\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\IrisCore\UHT",
                @"Runtime\Experimental\Iris\Core\Public",
                @"Runtime\Experimental\Iris",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\MovieSceneCapture\UHT",
                @"Runtime\MovieSceneCapture\Public",
                @"..\Intermediate\Build\Win64\UnrealEditor\Inc\AnimationDataController\UHT",
                @"Developer\AnimationDataController\Public",
                @"C:\Work\internal\EOS_OSB\EOS_OSB\Intermediate\Build\Win64\UnrealEditor\Inc\ExampleOSS\UHT",
                @"..\Plugins\Online\OnlineSubsystemUtils\Intermediate\Build\Win64\UnrealEditor\Inc\OnlineSubsystemUtils\UHT",
                @"..\Plugins\Online\OnlineSubsystemUtils\Source\OnlineSubsystemUtils\Classes",
                @"..\Plugins\Online\OnlineSubsystemUtils\Source\OnlineSubsystemUtils\Public",
                @"..\Plugins\Online\OnlineSubsystemUtils\Source",
                @"..\Plugins\Online\VoiceChat\VoiceChat\Source\Public",
                @"..\Plugins\Online\VoiceChat\VoiceChat",
                @"ThirdParty\mimalloc\include",
                @"ThirdParty\LibTiff\Source\Win64",
                @"ThirdParty\LibTiff\Source",
                @"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\INCLUDE",
                @"C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt",
                @"C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared",
                @"C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um",
                @"C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt",
            }.Select(x => Path.IsPathRooted(x) ? x : Path.Combine(enginePath, x)).ToArray();
            var globalDefinitions = new Dictionary<string, string>
            {
                { "_CRT_STDIO_LEGACY_WIDE_SPECIFIERS", "1" },
                { "_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS", "1" },
                { "_WINDLL", "1" },
                { "_DISABLE_EXTENDED_ALIGNED_STORAGE", "1" },
                { "PLATFORM_EXCEPTIONS_DISABLED", "0" },
            };

            var resolver = new DefaultPreprocessorResolver(new GenericInMemoryFilesystemExistenceProvider());

            var result = await resolver.ResolveAsync(
                new NonCachingPreprocessorScanner(),
                @"C:\Work\internal\EOS_OSB\EOS_OSB\Intermediate\Build\Win64\x64\UnrealEditor\DebugGame\ExampleOSS\Module.ExampleOSS.1_of_3.cpp",
                new[]
                {
                    pchPath,
                },
                includes,
                globalDefinitions,
                DateTimeOffset.UtcNow.Ticks,
                new CompilerArchitype
                {
                    Msvc = new MsvcCompiler
                    {
                        CppLanguageVersion = 201703 /* C++ 17 */,
                        MsvcVersion = 1935 /* 2022 17.5 */,
                        MsvcFullVersion = 193599999 /* Latest 2022 17.5 */,
                        CLanguageVersion = 201710 /* C 17 */,
                    },
                    TargetPlatformNumericDefines =
                    {
                        { "_WIN32", 1 },
                        { "_WIN64", 1 },
                        { "_WIN32_WINNT", 0x0601 /* Windows 7 */ },
                        { "_WIN32_WINNT_WIN10_TH2", 0x0A01 },
                        { "_WIN32_WINNT_WIN10_RS1", 0x0A02 },
                        { "_WIN32_WINNT_WIN10_RS2", 0x0A03 },
                        { "_WIN32_WINNT_WIN10_RS3", 0x0A04 },
                        { "_WIN32_WINNT_WIN10_RS4", 0x0A05 },
                        { "_NT_TARGET_VERSION_WIN10_RS4", 0x0A05 },
                        { "_WIN32_WINNT_WIN10_RS5", 0x0A06 },
                        { "_M_X64", 1 },
                        { "_VCRT_COMPILER_PREPROCESSOR", 1 },
                        /*
                         * Some undocumented define that the Windows headers rely on 
                         * for Compiled Hybrid Portable Executable (CHPE) support, 
                         * which is for x86 binaries that include ARM code. This
                         * undocumented feature has since been replaced with ARM64EC,
                         * so we don't need to actually support this; we just need the
                         * define so the headers work.
                         */
                        { "_M_HYBRID", 0 },
                    }
                },
                CancellationToken.None);
            Assert.True(result.DependsOnPaths.Count > 0, "Expected at least one path to be depended on.");
        }
    }
}
