kind: KubeProxyConfiguration
apiVersion: kubeproxy.config.k8s.io/v1alpha1
clientConnection:
  kubeconfig: "__KUBECONFIG__"
hostnameOverride: "__HOSTNAME__"
winkernel:
  networkName: "__NETWORK_NAME__"
  sourceVip: "__SOURCE_VIP__"
  enableDSR: true
featureGates:
  WinDSR: true
  WinOverlay: true
mode: "kernelspace"