kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: "__CA_CERT_FILE__"
authorization:
  mode: Webhook
clusterDomain: "__CLUSTER_DOMAIN__"
clusterDNS:
  - "__CLUSTER_DNS__"
runtimeRequestTimeout: "15m"
tlsCertFile: "__NODE_CERT_FILE__"
tlsPrivateKeyFile: "__NODE_KEY_FILE__"
registryNode: true
evictionHard: 
  nodefs.available: "0%"
  imagefs.available: "0%"
# These are Windows specific options that must be turned off
# because Windows doesn't support them.
resolvConf: ""
cgroupsPerQOS: false
enforceNodeAllocatable: []
# Required by Calico (but also on by default anyway).
enableDebuggingHandlers: true
# Required by Calico (but also the default value anyway).
hairpinMode: "promiscuous-bridge"