name: Upload Artifact
description: Upload a named artifact
inputs:
  UET_ARTIFACT_NAME:
    description: "The known name of the artifact."
    required: true
  UET_FRAMEWORK_TARGET:
    description: "The .NET framework identifier."
    required: true
runs:
  using: 'composite'
  steps:
    - name: Upload Timestamp
      if: ${{ inputs.UET_ARTIFACT_NAME == 'timestamp' }}
      uses: actions/upload-artifact@v4
      with:
        name: timestamp
        if-no-files-found: error
        path: |
          package.version

    - name: Upload UEFS Win
      if: ${{ inputs.UET_ARTIFACT_NAME == 'uefs-win' }}
      uses: actions/upload-artifact@v4
      with:
        name: uefs-win
        if-no-files-found: error
        path: |
          UET/Redpoint.Uefs.Daemon/bin/Release/${{ inputs.UET_FRAMEWORK_TARGET }}/win-x64/publish/uefs-daemon.exe
    - name: Upload Shim Win
      if: ${{ inputs.UET_ARTIFACT_NAME == 'shim-win' }}
      uses: actions/upload-artifact@v4
      with:
        name: shim-win
        if-no-files-found: error
        path: |
          UET/uet.shim/bin/Release/${{ inputs.UET_FRAMEWORK_TARGET }}/win-x64/publish/uet.exe
    - name: Upload Pass 1 Win
      if: ${{ inputs.UET_ARTIFACT_NAME == 'pass-1-win' }}
      uses: actions/upload-artifact@v4
      with:
        name: pass-1-win
        if-no-files-found: error
        path: |
          UET/uet/bin/Release/${{ inputs.UET_FRAMEWORK_TARGET }}/win-x64/publish/uet.exe
    - name: Upload Pass 2 Win
      if: ${{ inputs.UET_ARTIFACT_NAME == 'pass-2-win' }}
      uses: actions/upload-artifact@v4
      with:
        name: pass-2-win
        if-no-files-found: error
        path: |
          UET/uet/bin/Release/${{ inputs.UET_FRAMEWORK_TARGET }}/win-x64/publish/uet.exe
        
    - name: Upload UEFS Mac
      if: ${{ inputs.UET_ARTIFACT_NAME == 'uefs-mac' }}
      uses: actions/upload-artifact@v4
      with:
        name: uefs-mac
        if-no-files-found: error
        path: |
          UET/Redpoint.Uefs.Daemon/bin/Release/${{ inputs.UET_FRAMEWORK_TARGET }}/osx-arm64/publish/uefs-daemon
    - name: Upload Shim Mac
      if: ${{ inputs.UET_ARTIFACT_NAME == 'shim-mac' }}
      uses: actions/upload-artifact@v4
      with:
        name: shim-mac
        if-no-files-found: error
        path: |
          UET/uet.shim/bin/Release/${{ inputs.UET_FRAMEWORK_TARGET }}/osx-arm64/publish/uet
    - name: Upload Pass 1 Mac
      if: ${{ inputs.UET_ARTIFACT_NAME == 'pass-1-mac' }}
      uses: actions/upload-artifact@v4
      with:
        name: pass-1-mac
        if-no-files-found: error
        path: |
          UET/uet/bin/Release/${{ inputs.UET_FRAMEWORK_TARGET }}/osx-arm64/publish/uet
    - name: Upload Pass 2 Mac
      if: ${{ inputs.UET_ARTIFACT_NAME == 'pass-2-mac' }}
      uses: actions/upload-artifact@v4
      with:
        name: pass-2-mac
        if-no-files-found: error
        path: |
          UET/uet/bin/Release/${{ inputs.UET_FRAMEWORK_TARGET }}/osx-arm64/publish/uet

    - name: Upload Shim Linux
      if: ${{ inputs.UET_ARTIFACT_NAME == 'shim-linux' }}
      uses: actions/upload-artifact@v4
      with:
        name: shim-linux
        if-no-files-found: error
        path: |
          UET/uet.shim/bin/Release/${{ inputs.UET_FRAMEWORK_TARGET }}/linux-x64/publish/uet
    - name: Upload Pass 1 Linux
      if: ${{ inputs.UET_ARTIFACT_NAME == 'pass-1-linux' }}
      uses: actions/upload-artifact@v4
      with:
        name: pass-1-linux
        if-no-files-found: error
        path: |
          UET/uet/bin/Release/${{ inputs.UET_FRAMEWORK_TARGET }}/linux-x64/publish/uet
    - name: Upload Pass 2 Linux
      if: ${{ inputs.UET_ARTIFACT_NAME == 'pass-2-linux' }}
      uses: actions/upload-artifact@v4
      with:
        name: pass-2-linux
        if-no-files-found: error
        path: |
          UET/uet/bin/Release/${{ inputs.UET_FRAMEWORK_TARGET }}/linux-x64/publish/uet

    - name: Upload Libs Win
      if: ${{ inputs.UET_ARTIFACT_NAME == 'libs-win' }}
      uses: actions/upload-artifact@v4
      with:
        name: libs-win
        if-no-files-found: error
        path: |
          **/*.nupkg
    - name: Upload Libs Mac
      if: ${{ inputs.UET_ARTIFACT_NAME == 'libs-mac' }}
      uses: actions/upload-artifact@v4
      with:
        name: libs-mac
        if-no-files-found: error
        path: |
          **/*.nupkg

    - name: Upload Windows Test Results
      if: ${{ inputs.UET_ARTIFACT_NAME == 'test-results-win' }}
      uses: actions/upload-artifact@v4
      with:
        name: test-results-win
        if-no-files-found: error
        path: |
          TestResults/*.test-result.trx
    - name: Upload Linux Test Results
      if: ${{ inputs.UET_ARTIFACT_NAME == 'test-results-linux' }}
      uses: actions/upload-artifact@v4
      with:
        name: test-results-linux
        if-no-files-found: error
        path: |
          TestResults/*.test-result.trx
    - name: Upload Cloud Framework Test Results
      if: ${{ inputs.UET_ARTIFACT_NAME == 'test-results-cf' }}
      uses: actions/upload-artifact@v4
      with:
        name: test-results-cf
        if-no-files-found: error
        path: |
          TestResults/*.test-result.trx

    - name: Upload Helm Chart
      if: ${{ inputs.UET_ARTIFACT_NAME == 'helm-chart' }}
      uses: actions/upload-artifact@v4
      with:
        name: helm-chart
        if-no-files-found: error
        path: |
          UET/Lib/Helm/*.tgz