name: Publish Test Results

on:
  workflow_run:
    workflows: ["Unreal Engine Tool"]
    types:
      - completed

permissions: {}

jobs:
  test-results:
    name: Test Results
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'
    permissions:
      checks: write
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: test-results
        path: TestResults/
        run-id: ${{ github.event.workflow_run.id }}
    - name: Report Test Results
      uses: dorny/test-reporter@v1
      with:
        name: Windows Test Results
        path: TestResults/*.test-result.trx
        reporter: dotnet-trx